### ISSUE TITLE
Custom emotes don't seem to work

### ISSUE THREAD

**Issue by Atlas7005** [dogegarden/dogehouse.js#30]
I'm just getting the hang of this library, even tho there's no documentation _(pls fix)_  
And I can't seem to figure out how to send emotes. I thought it would be similar to when creating Twitch bots where you just send the name _( in this case surrounded in : )_ but that just sends the plain-text ":peepoHappy:"

**Comment by HoloPanio** [comment]
Currently you must make an array to send custom emotes.  We use a utility that allows us to compile strings and custom arrays to message objects for dogehouse.  I will put in a word with the contributor who created the utility to see if we can work out a way to setup up plain test emotes and mentions.

If you would like to send an emoji, you must set your message to the following.
```js
["My favorite emoji is ", { emoji: "peepoHappy" }, " because it makes me happy." ]
```
This string is the equivalent of typing `My favorite emoji is :peepoHappy: because it makes me happy`

**Comment by BronzW** [comment]
How do you do this with text formatting? Because I have the same issue when trying to use backticks to make it look like this: `test`

**Comment by BronzW** [comment]
What is the option for that?

**Comment by HoloPanio** [comment]
> How do you do this with text formatting? Because I have the same issue when trying to use backticks to make it look like this: `test`

There is currently no way to do markdown formatting in chat just yet, but there has been an update to the message compiler, you can now put emotes, mentions, and links into a message and it will automatically be converted to it's appropriate type and value tokens.
